# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildWindows:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install spinehaxe
          haxelib install hscript
          haxelib install hxcpp-debug-server
          haxelib install actuate
          haxelib install hxCodec 2.5.1
          haxelib install hscript-iris 1.1.3
          haxelib install tjson 1.4.0
          haxelib install hxdiscord_rpc 1.2.4
          haxelib git discord_rpc_yce https://github.com/LEON-BROTHER/discord_rpc_yce
          haxelib git hxvm-luajit https://github.conebulazorua/hxvm-luajit
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib git flixel-textureatlas-yoshiengine https://github.com/Smokey555/Flixel-TextureAtlas
          haxelib git hscript-yoshiengine https://github.com/YoshiCrafter29/hscript-improved
          haxelib git flixel-yc29 https://github.com/YoshiCrafter29/flixel
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
          haxelib git spinehaxe https://github.com/bendmorris/spinehaxe
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib list
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile Windows
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild
          path: export/release/windows/bin
