#
# Stolen from AbnormalPoof's fork, didnt knew workflows existed lmao
#

# This is a basic workflow to help you get started with Actions

name: COMPILE ON WINDOWS

# Controls when the workflow will run
on:
  push:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      - uses: krdlab/setup-haxe@main
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: funny dependencies
        run: |
          mkdir "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          Haxelib install lime 8.1.2
          Haxelib install openfl 9.3.3
          Haxelib install flixel 5.6.1
          Haxelib install flixel-addons 3.2.2
          Haxelib install flixel-tools 1.5.1
          Haxelib install hscript-iris 1.1.3
          Haxelib install tjson 1.4.0
          haxelib install hxdiscord_rpc 1.2.4
          haxelib install hxvlc 1.9.2
          haxelib install flixel-ui
          haxelib install spinehaxe
          haxelib git discord_rpc_yce https://github.com/YoshiCrafter29/linc_discord-rpc
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib git flixel-textureatlas-yoshiengine https://github.com/Smokey555/Flixel-TextureAtlas
          haxelib git hscript-yoshiengine https://github.com/CodenameCrew/hscript-improved
          haxelib git flixel-yc29 https://github.com/Yoshman29-FunkinArchive/flixel
          haxelib git spinehaxe https://github.com/bendmorris/spinehaxe
          haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate 768740a56b26aa0c072720e0d1236b94afe68e3e
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit 1906c4a96f6bb6df66562b3f24c62f4c5bba14a7
          haxelib git funkin.vis https://github.com/FunkinCrew/funkVis 22b1ce089dd924f15cdc4632397ef3504d464e90
          haxelib git grig.audio https://gitlab.com/haxe-grig/grig.audio.git cbf91e2180fd2e374924fe74844086aab7891666
      - name: compilation
        run: |
          haxelib run lime build windows -dce no
          
      - uses: actions/upload-artifact@main
        with:
          name: YoshiCrafterEngine
          path: export/release/windows/bin
